app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index),
    path('members/', include('members.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('shows/', include('shows.urls')),
]

urlpatterns += static(
            prefix=settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login-view'),
    path('logout/', views.logout_view, name='logout-view'),
    path('user_pick/', views.user_pick, name='user-pick'),
]

app/shows/urls.py
from django.urls import path

from . import views

app_name = 'shows'

urlpatterns = [
    path('show_list/', views.show_list, name='show-list'),
    path('show_detail/<int:show_pk>/', views.show_detail, name='show-detail'),
    path('show_rating/<int:rating_score>/', views.show_rating, name='show-rating'),
    path('<int:show_pk>/comment/create', views.comment_create, name='comment_create'),
    path('<int:show_pk>/pick_toggle/', views.show_pick_toggle, name='show_pick_toggle'),
    path('search_list/<str:keyword>/', views.search_list, name='search_list'),
    path('search/', views.keyword_search, name='keyword-search'),
]

app/members/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

app/shows/models.py
from django.contrib.auth import get_user_model
from django.db import models
User = get_user_model()
# Create your models here.


class Show(models.Model):
    title = models.CharField('전시명', max_length=50)
    period = models.CharField('전시기간', max_length=200)
    place = models.CharField('전시장소', max_length=200)
    thumbnail = models.ImageField('썸네일', upload_to='thumbnail')
    poster = models.ImageField('포스터', upload_to='poster')
    description = models.TextField('상세설명', blank=True, null=True)
    price = models.PositiveIntegerField('가격', default=0)
    created_at = models.DateTimeField('작성일자', auto_now_add=True)
    web_link = models.URLField('웹주소', max_length=200, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '전시'
        verbose_name_plural = f'{verbose_name} 목록'
        ordering = ['-pk']

    def pick_toggle(self, user):
        # 전달받은 user가 이 전시회를 이미 pick했다면 pick 해제
        # 안되어있다면 pick처리
        showpick, showpick_created = self.showpick_set.get_or_create(user=user)
        if not showpick_created:
            showpick.delete()

    pick_users = models.ManyToManyField(
        User,
        through='ShowPick',
        related_name='pick_shows',
        related_query_name='pick_show',
    )


class Comment(models.Model):
    show = models.ForeignKey(
        Show,
        on_delete=models.CASCADE,
        verbose_name='전시회',
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='작성자',
    )
    content = models.TextField('댓글 내용')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = f'{verbose_name} 목록'

    def __str__(self):
        return f'[{self.author.username}]이/가 글[{self.show.title}]에 댓글: {self.content}'


class ShowPick(models.Model):
    show = models.ForeignKey(
        Show,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # 특정 User가 특정 전시회를 Pick한 정보는 unique해야함
        unique_together = (
            ('show', 'user'),
        )

    def __str__(self):
        return f'[{self.user.username}]이/가 [{self.show.title}]를 찜'


class Rating(models.Model):
    show = models.ForeignKey(
        Show,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    # 나중에 최고점 5 점으로 수정하는 알고리즘을 넣어야
    score = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # 특정 User가 특정 전시회를 rating한 정보는 unique해야함
        unique_together = (
            ('show', 'user'),
        )

    def __str__(self):
        return f'[{self.user.username}]이 [{self.show.title}]에 {self.score}점 줌 '

app/shows/forms.py
from django import forms

from .models import Comment, Rating


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 2,
                }
            )
        }


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['score']

app/config/views.py
from django.shortcuts import redirect


def index(request):
    return redirect('members:login-view')

app/members/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect

from shows.models import Show


def login_view(request):
    return render(request, 'members/login.html')


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('shows:show-list')
    else:
        pass


# 사용자가 찜한 목록 보기
def user_pick(request):
    shows = Show.objects.filter(showpick__user=request.user)
    context = {
        "shows": shows,
    }
    return render(request, 'members/user_pick.html', context)

app/shows/views.py
from django.shortcuts import render, get_object_or_404, redirect

# 전체 리스트
from .forms import CommentForm
from .models import Show


def show_list(request):
    shows = Show.objects.all()
    content = {
        'shows': shows,
        'comment_form': CommentForm(),
    }
    return render(request, 'shows/show_list.html', content)


# 전시회 상세보기
def show_detail(request, show_pk):
    show = get_object_or_404(Show, pk=show_pk)
    comments = show.comments.all()
    content = {
        'show': show,
        'comments': comments,
    }
    return render(request, 'shows/show_detail.html', content)


# 특정 rating 이상 보기
def show_rating(request, rating_score):
    return render(request, 'show/show_rating.html')


# comment 작성
def comment_create(request, show_pk):
    if request.method == 'POST':
        show = Show.objects.get(pk=show_pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.show = show
            comment.save()
            comments = show.comments.all()
            content = {
                'show': show,
                'comments': comments,
            }
            return render(request, 'shows/show_detail.html', content)


def show_pick_toggle(request,show_pk):

    if request.method == 'POST':
        show = get_object_or_404(Show, pk=show_pk)
        show.pick_toggle(request.user)
        comments = show.comments.all()
        content = {
            'show': show,
            'comments': comments,
        }
        return render(request, 'shows/show_detail.html', content)


def search_list(request, keyword):
    shows = Show.objects.filter(title__contains=keyword)
    context = {
        'keyword': keyword,
        'shows': shows,
    }
    return render(request, 'shows/search_show_list.html', context)


def keyword_search(request):
    # request.GET으로 전달된 search_keyword값을
    # 위의  tag_post_list view로 redirect
    search_keyword = request.GET.get('search_keyword')
    return redirect('shows:search_list', search_keyword)

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>전시관이 살아있다</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <style>
        img {
            max-width: 100%;
        }
    </style>
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '546322495811516',
                xfbml: true,
                version: 'v3.2'
            });
            FB.AppEvents.logPageView();
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {
                return;
            }
            js = d.createElement(s);
            js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
</head>
<body>
<div id="wrap">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #F9A31F">
        <a href="{% url 'shows:show-list' %}" class="navbar-brand">
            <i class="far fa-thumbs-up"></i>
            전시관이 살아있다</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <form id="search-form" action="{% url 'shows:keyword-search' %}" class="form-inline my-2 my-lg-0">
            <input id="search-input" class="form-control mr-sm-3" type="search" placeholder="관심있는 내용을 검색해봐요"
                   aria-label="Search" name="search_keyword">
            <button id="search-button" class="btn btn-outline-light my-2 my-sm-0" type="submit">검색</button>
        </form>
        <!--<form class="form-inline my-2 my-lg-0">-->
            <!--<input class="form-control mr-sm-3" type="search" placeholder="관심있는 내용을 검색해봐요" aria-label="Search">-->
            <!--<button class="btn btn-outline-light my-2 my-sm-0" type="submit">검색</button>-->
        <!--</form>-->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-md-auto">
                <li class="nav-item active">
                    <a class="btn btn-outline-light my-2 mr-sm-0" href="{% url 'shows:show-list' %}">Home<span
                            class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a href="{% url 'members:user-pick' %}" class="btn btn-outline-light my-2 mr-sm-0">내가 찜한 전시</a>
                    </li>
                    <li class="nav-item active">
                        <form action="{% url 'members:logout-view' %}" method="POST" class="form-inline my-2 my-lg-0">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-light my-2 mr-sm-0">로그아웃</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a href="{% url 'members:login-view' %}" class="btn btn-outline-light my-2 mr-sm-0">로그인</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
</div>
</body>
</html>

app/templates/members/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="col col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2">
        <h2 class="text-center">로그인</h2>
        <a class="btn btn-outline btn-block" href="{% url 'social:begin' 'facebook' %}">
            <i class="fab fa-facebook"></i>
            Facebook으로 로그인</a>
        <a class="btn btn-outline btn-block" href="{% url 'social:begin' 'google-oauth2' %}">
            <i class="fab fa-google"></i>
            Google로 로그인</a>
    </div>
{% endblock %}

app/templates/members/user_pick.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h2>내가 찜한 목록</h2>
        <div class="row">
            {% for show in shows %}
                <div class="col-4">
                    <div class="card">
                        <img class="card-img-top" src="{{ show.thumbnail.url }}">
                        <div class="card-body">
                            <div class="card-title">
                                <a href="{% url 'shows:show-detail' show_pk=show.pk %}">
                                    <h5 class="card-title">{{ show.title }}</h5>
                                </a>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">전시관 : {{ show.place }}</li>
                                <li class="list-group-item">전시기간: {{ show.period }}</li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <a href="{% url 'shows:show-detail' show_pk=show.pk %}" class="card-link">자세한 내용보기</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/shows/search_show_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div>
        <h2 >검색 결과: {{ keyword }}</h2>
        <div class="row">
            {% for show in shows %}

                <div class="col-4">
                    <div class="card">
                        <img class="card-img-top" src="{{ show.thumbnail.url }}">
                        <div class="card-body">
                            <div class="card-title">
                                <a href="{% url 'shows:show-detail' show_pk=show.pk %}">
                                    <h5 class="card-title">{{ show.title }}</h5>
                                </a>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">전시관 : {{ show.place }}</li>
                                <li class="list-group-item">전시기간: {{ show.period }}</li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <a href="{% url 'shows:show-detail' show_pk=show.pk %}" class="card-link">자세한 내용보기</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/shows/show_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div>
        <div class="container">
            <div>
                <h2>{{ show.title }}</h2>
                <hr width="100%" color="orange" size="3">
            </div>
            <div class="row">
                <div class="col">
                    <img src="{{ show.thumbnail.url }}" width="100%">
                </div>
                <div class="col">
                    <h4>장소</h4>
                    <p>{{ show.place }}</p>
                    <h4>기간</h4>
                    <p>{{ show.period }}</p>
                    <h4>티켓 구매하기</h4>
                    <a href="{{ show.web_link }}">예매 페이지로 이동하기</a>
                    <!--찜하기-->
                    {% if user.is_authenticated %}
                        <form action="{% url 'shows:show_pick_toggle' show_pk=show.pk %}" method="POST">
                            {% csrf_token %}
                            {% if user in show.pick_users.all %}
                                <button class="btn btn-outline-light bg-danger" type="submit">
                                    <i class="fas fa-heart"></i>
                                    찜해제
                                </button>
                            {% else %}
                                <button class="btn btn-outline-light bg-danger" type="submit">
                                    <i class="far fa-heart"></i>
                                    찜
                                </button>
                            {% endif %}
                        </form>
                    {% endif %}
                    <!--찜하기 끝-->
                </div>
                <hr width="100%" color="orange" size="3">
            </div>
            <div>
                <img src="{{ show.poster.url }}">
                <hr width="100%" color="orange" size="3">
            </div>
            <div class="card" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title">상세 안내</h5>
                    <p class="card-text">{{ show.description }}</p>
                </div>

            </div>
            <hr width="100%" color="orange" size="3">

            <div>
                <div>
                    <h3>댓글</h3>
                    <ul class="card-body">
                        {% for comment in comments %}
                            <li class="list-group-item">{{ comment.author }}: {{ comment.content }}
                            </li>
                        {% endfor %}
                    </ul>

                    <!--댓글 작성-->
<h3>댓글작성</h3>

                    {% if user.is_authenticated %}
                        <form action="{% url 'shows:comment_create' show_pk=show.pk %}" method="POST">
                            {% csrf_token %}
                            {{ comment_form.content }}
                            <textarea name="content" class="form-control" aria-label="With textarea"></textarea>
                            <button type="submit" class="btn btn-outline-dark my-2 my-sm-0">작성</button>
                        </form>
                    {% endif %}
                </div>
                <hr width="100%" color="orange" size="3">
            </div>
        </div>
    </div>
{% endblock %}

app/templates/shows/show_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div>
        <h2 >전체 전시회 목록 보기</h2>
        <div class="row">
            {% for show in shows %}

                <div class="col-4">
                    <div class="card">
                        <img class="card-img-top" src="{{ show.thumbnail.url }}">
                        <div class="card-body">
                            <div class="card-title">
                                <a href="{% url 'shows:show-detail' show_pk=show.pk %}">
                                    <h5 class="card-title">{{ show.title }}</h5>
                                </a>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">전시관 : {{ show.place }}</li>
                                <li class="list-group-item">전시기간: {{ show.period }}</li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <a href="{% url 'shows:show-detail' show_pk=show.pk %}" class="card-link">자세한 내용보기</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/shows/show_rating.html
{% extends 'base.html' %}

{% block content %}
<h2>특정 rating 이상 전시 목록 보기</h2>
{% endblock %}